#!/bin/sh

export NUM=0;
for session in $(tmux ls \
  | egrep '^[0-9]+:' \
  | awk '{ print substr($1,1,length($1)-1) }' \
  | sort -g)
do
  if [ "$NUM" != "$session" ]
  then 
    break; 
  fi
  NUM=$((NUM+1))
done
echo $NUM
