#!/bin/sh

export NUM=0;
for session in $(/opt/homebrew/bin/tmux ls \
  | egrep '^[0-9]+:' \
  | awk '{ print substr($1,1,length($1)-1) }' \
  | sort -g)
do
  echo $NUM >> ~/hmm.txt
  if [ "$NUM" != "$session" ]
  then 
    break; 
  fi
  NUM=$((NUM+1))
  echo $NUM >> ~/hmm.txt
done
echo $NUM >> ~/wot.txt
echo $NUM
